// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oeptrkzeixrkvmfygdwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcHRya3plaXhya3ZtZnlnZHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMTk1NDAsImV4cCI6MjA4ODc5NTU0MH0.ig-rGHCGFPExIGS0BKk2iz1uCb1Mctk-RV38LUhFC_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);